- name: configure "{{ component }}"
  become: yes
  #hosts: "{{ component }}"
  hosts: localhost # This is to run the playbook on localhost in terraform
  connection: local
  roles:
  - "{{ component }}"